apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: capi-visualizer
spec:
  clusterSelector:
    matchLabels:
      clusterApiVisualizerChart: enabled
  repoURL: https://charts.christianhuth.de
  chartName: cluster-api-visualizer
  namespace: default
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  valuesTemplate: ""
