apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: external-secrets
spec:
  clusterSelector:
    matchLabels:
      externalSecretsChart: enabled
  repoURL: https://charts.external-secrets.io
  chartName: external-secrets
  namespace: external-secrets
  releaseName: external-secrets
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
  valuesTemplate: ""
