apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: hcloud-ccm
spec:
  clusterSelector:
    matchLabels:
      hcloudCcmChart: enabled
  repoURL: https://charts.syself.com
  chartName: ccm-hcloud
  namespace: kube-system
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  valuesTemplate: |
    secret:
      name: hetzner
      tokenKeyName: hcloud
    privateNetwork:
      enabled: "false"
