apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: kyverno
spec:
  clusterSelector:
    matchLabels:
      kyvernoChart: enabled
  repoURL: https://kyverno.github.io/kyverno/
  chartName: kyverno
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
  valuesTemplate: {}
