apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: metrics-server
spec:
  clusterSelector:
    matchLabels:
      metricsServerChart: enabled
  repoURL: https://kubernetes-sigs.github.io/metrics-server/
  chartName: metrics-server
  namespace: kube-system
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  valuesTemplate: ""
