apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: secrets-store-csi-driver
spec:
  clusterSelector:
    matchLabels:
      secretStoreCsiDriverChart: enabled
  repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  chartName: secrets-store-csi-driver
  namespace: vault
  releaseName: secrets-store-csi-driver
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
  valuesTemplate: |
    syncSecret:
      enabled: true
